name: simple_todo
description: A simple Todo App

publish_to: 'none'

version: 1.1.1+3

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.9
  intl: ^0.18.1
  drift: ^2.9.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3
  get_it: ^7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  drift_dev: ^2.9.0
  build_runner: ^2.4.5


flutter:
  uses-material-design: true

  fonts:
    - family: Pretendard
      fonts:
        - asset: asset/font/Pretendard-Regular.otf
          weight: 400
        - asset: asset/font/Pretendard-Bold.otf
          weight: 700